# Generated by Django 4.2.1 on 2023-06-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_options', models.CharField(choices=[('M-pesa', 'M-Pesa'), ('Pay on Delivery', 'Pay on Delivery')], max_length=64)),
                ('payment_date', models.DateField()),
                ('receipt', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=15)),
                ('order', models.CharField(max_length=64)),
            ],
        ),
    ]
