# Generated by Django 4.2.1 on 2023-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_options',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(default='WER5432', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(default='23ew4', max_length=32),
            preserve_default=False,
        ),
    ]
