# Generated by Django 4.2.1 on 2023-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_payment_time_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunds',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
