# Generated by Django 4.2.1 on 2023-06-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_remove_shipment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='delivery_options',
            new_name='delivery_method',
        ),
    ]
