# Generated by Django 4.2.3 on 2023-07-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
