# Generated by Django 4.2.1 on 2023-06-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_name',
            field=models.CharField(max_length=120),
        ),
    ]
