# Generated by Django 4.2.1 on 2023-06-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number_products', models.PositiveIntegerField()),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_options', models.CharField(max_length=12)),
                ('payment_options', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Pay on Delivery', 'Pay on Delivery')], max_length=15)),
            ],
        ),
    ]
