# Generated by Django 4.2.1 on 2023-06-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='number_products',
            new_name='number_of_products',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='total_products',
            new_name='products_total',
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_options',
            field=models.CharField(choices=[('Pick-Up Point', 'Pick-Up Point'), ('Home Delivery', 'Home Delivery')], max_length=15),
        ),
    ]
