# Generated by Django 4.2.1 on 2023-06-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_number_of_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='delivery_options',
            new_name='delivery_method',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='payment_options',
            new_name='payment_method',
        ),
    ]
