# Generated by Django 4.2.3 on 2023-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_payment'),
        ('cart', '0004_rename_delivery_options_cart_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ManyToManyField(to='order.order'),
        ),
    ]
