# Generated by Django 4.2.3 on 2023-08-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_image'),
        ('cart', '0006_remove_cart_order_cart_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='inventory',
        ),
        migrations.AddField(
            model_name='cart',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
