# Generated by Django 4.2.3 on 2023-08-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_image'),
        ('cart', '0007_remove_cart_inventory_cart_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='inventory',
        ),
        migrations.AddField(
            model_name='cart',
            name='inventory',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
