# Generated by Django 4.2.1 on 2023-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone_Number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=32)),
            ],
        ),
    ]
