# Generated by Django 4.2.1 on 2023-06-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='gokowanjiru@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
