# Generated by Django 4.2.1 on 2023-06-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_customer_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
    ]
