# Generated by Django 4.2.1 on 2023-06-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_date_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_options',
            field=models.CharField(choices=[('Pick-Up Point', 'Pick-Up Point'), ('Home Delivery', 'Home Delivery')], max_length=15),
        ),
    ]
