# Generated by Django 4.2.1 on 2023-06-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_delivery_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_options',
            new_name='delivery_method',
        ),
    ]
