# Generated by Django 4.2.3 on 2023-07-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
