# Generated by Django 4.2.3 on 2023-07-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_location_order_name_order_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
